### PR TITLE
[ng] docs(server-communication): fix bootstrap provider for BrowserClient

### LINKED ISSUE #332: [ng] http guide - Cannot find reflection information on BrowserClient exception
Hi,

if I register the `BrowserClient` according to the guide here: https://webdev.dartlang.org/angular/guide/server-communication#!#http-client

e.g.: 
```dart
bootstrap(AppComponent, const [BrowserClient]);
```

I get the "Exception: Cannot find reflection information on BrowserClient" ([the issue](https://github.com/angular/angular.io/issues/2347)).

I think that you should explicitly mention, that until this problem is fixed, devs need to use the longer the version:

e.g.:
```dart
bootstrap(AppComponent, [provide(BrowserClient, useFactory: () => new BrowserClient(), deps: [])]);
```

P.S.: The example is ok:
https://github.com/angular-examples/server-communication/blob/master/web/main.dart

### PR DESCRIPTION
**Pull request by chalin**
This updates the bootstrap provider for BrowserClient based on what we've been doing in the toh-6.

Fixes #332

### CODE REVIEW

File: public/docs/_examples/server-communication/dart/web/main.dart [hunk 1]
```diff
@@ -19,16 +18,16 @@ void main() {
...
-    // https://github.com/angular/angular/issues/5266
   ]);
 }
 // #enddocregion final, in-mem-web-api-providers
 /*
 // #docregion v1
 
 void main() {
-  bootstrap(AppComponent, const [BrowserClient]);
+  bootstrap(AppComponent, [
```
Comment (kwalrath) [inline public/docs/_examples/server-communication/dart/web/main.dart]: The new code is so much longer and harder to read. Can we really not use `const [BrowserClient])`?

Comment (chalin) [inline public/docs/_examples/server-communication/dart/web/main.dart]: As you might recall, I had originally filed an issue over AngularDart for this (https://github.com/dart-lang/angular2/issues/37), but [at the time Matan suggested that it WAI](https://github.com/dart-lang/angular2/issues/37#issuecomment-240907806). So, unless issue 37 is reopened and fixed we _must_ write the provider expression in the longer format.

Comment (kwalrath) [inline public/docs/_examples/server-communication/dart/web/main.dart]: OK :(

@matanlurey is there any way to simplify this code?
